### ISSUE TITLE
replace key using an index of the array 

### ISSUE THREAD

**Issue by DuaaH** [GSG-K3/news-translation-react#23]
using the index of the array as a key is bad practice.
you could read the documentation to understand correctly.

https://github.com/GSG-K3/news-translation-react/blob/e0a3209463a334da004f324962f3648ba780f1c3/src/Components/News.js#L12-L15

**Comment by tasneembhiri** [comment]
{this.props.articles.map((item) => {
          return (
            <ul key={item.toString()}>
              <li>
@DuaaH  is this better???

**Comment by DuaaH** [comment]
@tasneembhiri 
if you have an id from the API I think its better, and we put the key for a list item in the ul.
<ul>
      {props.posts.map((post) =>
        <li key={post.id}>
          {post.title}
        </li>
      )}
    </ul>
